### ISSUE TITLE
Removing and adding a chart back throwing an error

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/iViz#166]
![screen shot 2016-08-15 at 9 36 55 am](https://cloud.githubusercontent.com/assets/12956870/17665947/d474a5f0-62cb-11e6-8e06-cbaf5d6a1832.png)

**Comment by kalletlak** [comment]
This is because of crossfilter dimension restrictions(32 charts)

**Comment by yichaoS** [comment]
![image](https://cloud.githubusercontent.com/assets/5973438/17791993/7015f368-656c-11e6-9296-be06321b986f.png)

**Comment by yichaoS** [comment]
![image](https://cloud.githubusercontent.com/assets/5973438/17791996/75fea02c-656c-11e6-8918-218c1424716c.png)
when deleting charts

**Comment by kalletlak** [comment]
Fixed in PR #171
