### ISSUE TITLE
Styling issue on chart mousevoer and when chart is filtered

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/iViz#189]
![aug-31-2016 11-51-08](https://cloud.githubusercontent.com/assets/12956870/18135869/6166fe52-6f71-11e6-9aed-1a98b7498027.gif)

**Comment by zhx828** [comment]
This issue is back.
![screen shot 2016-09-29 at 11 55 51 am](https://cloud.githubusercontent.com/assets/5400599/18961676/cfbe90aa-863b-11e6-8bc6-b1debb08eca9.png)

**Comment by kalletlak** [comment]
Probably this is because of additional icon(info icon) in the header.
