### ISSUE TITLE
Fix TODO

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/iViz#21]
- [x] Sample to patient (find the better way to do the mapping)
- [x] Need to find the case_set_id from the web api.

**Comment by yichaoS** [comment]
Didn't do "finding case_set_id from web api" since it's always the case, that the most complete list of patient ids' CASE_SET_ID is STUDY_ID + "_all". @jjgao @zhx828

**Comment by yichaoS** [comment]
https://github.com/zhx828/cbioportal/pull/14
