### ISSUE TITLE
Survival curve is different when compared to the one which is generated in cBioPortal

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/iViz#214]
In cBioportal
<img width="294" alt="screen shot 2016-09-09 at 11 40 54 am" src="https://cloud.githubusercontent.com/assets/12956870/18393193/7a24eb8a-7682-11e6-9c6b-f68b388a9edc.png">

In iViz
<img width="294" alt="screen shot 2016-09-09 at 11 41 05 am" src="https://cloud.githubusercontent.com/assets/12956870/18393194/7a2616e0-7682-11e6-88e1-a8784bd3a667.png">

This is for study : chol_nus_2012

**Comment by yichaoS** [comment]
Data is different for one patient. And the event is decease. Which database are you using

**Comment by kalletlak** [comment]
I am using the cbio web api's. So it should be pointing to cbioportal.org database

**Comment by yichaoS** [comment]
I'm using the development database. Lemme switch to another branch of the code and test with the same database to double check.

**Comment by kalletlak** [comment]
Found one more difference
In cBIoPortal we are showing sample id on mouseover and in iViz we are showing patient id. Is this an update?

**Comment by yichaoS** [comment]
Yes, this is a very critical update :) survival study is patient based, never sample based.
