### ISSUE TITLE
Number of samples for a study is different in iViz when compared to cBioPortal study-view

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/iViz#216]
Example for studies : gbm_tcga_pub

in cBioportal

<img width="500" alt="screen shot 2016-09-09 at 12 55 58 pm" src="https://cloud.githubusercontent.com/assets/12956870/18395575/f91d4978-768c-11e6-84a1-e64bf011bdba.png">

in iViz

<img width="500" alt="screen shot 2016-09-09 at 12 56 14 pm" src="https://cloud.githubusercontent.com/assets/12956870/18395574/f91a588a-768c-11e6-80e3-59521b239f79.png">

Similar issue even in pcnsl_mayo_2015 study

**Comment by zhx828** [comment]
Issue created in cBioPortal https://github.com/cBioPortal/cbioportal/issues/1663

**Comment by zhx828** [comment]
Since iViz starts to use cases from _all list. There should be any difference any more.
