### ISSUE TITLE
add option to remove NA 

### ISSUE THREAD

**Issue by JiaoJiao123** [cBioPortal/iViz#236]
For some bar chart which has quite amount of data are NA, it is hard to see the distribution of the real useful data. 
<img width="1177" alt="dc06d0fa-721a-11e6-927a-10585ff694ca" src="https://cloud.githubusercontent.com/assets/13951023/18453494/87d69ea8-790d-11e6-898b-f7b30dc33ac9.png">
proposed solution: provide option to remove NA values in the bar chart

**Comment by kalletlak** [comment]
This is fixed. Currently we show chart depending on the the priority.
