### ISSUE TITLE
OS_MONTHS AND OS_STATUS are present but without any data

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/iViz#243]
Study: acc_tcga

**Comment by kalletlak** [comment]
I didn't find OS_MONTHS attribute for this study

**Comment by zhx828** [comment]
If the clinical attributes are present in the database, that means there are some data for them. If in reality, there is nothing for this clinical attribute but still in the database, they need to clean it up.

**Comment by zhx828** [comment]
We now show a message saying this study does not have any data.
