### ISSUE TITLE
scope.clearAll is not a function

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/iViz#258]
After selecting four categories in CancerTypeDetailed, the console returns error if you click clear all button
![screen shot 2016-09-15 at 11 20 38 am](https://cloud.githubusercontent.com/assets/5400599/18555607/76b3594c-7b36-11e6-82a3-dd528db53e5d.png)

**Comment by kalletlak** [comment]
Event this is because of not all changes from index.html moved into dcplots.jsp
