### ISSUE TITLE
Design the entry point to virtual cohort

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/iViz#350]
In the current prototype, we are using the study selection tree and a "Dashboard" button to merge multiple studies.

**Comment by cdvfitz** [comment]
@jjgao want to have a call next week to discuss? I've got time Wednesday between 11-3.

**Comment by jjgao** [comment]
@cdvfitz sounds good. How about 11am?

**Comment by jjgao** [comment]
@cdvfitz and I had a quick meeting. We though the current `Dashboard` button is not intuitive and come with two options.

1. Add a new button `View Studies` to `Query` button (currently, `Query` is called `Submit`)
2. Use the same button for  `View Studies` and `Query` -- switching based on whether a gene is entered.

![image](https://cloud.githubusercontent.com/assets/840895/22079514/2aec0070-dd8a-11e6-8290-b3b6e9977a84.png)
