### ISSUE TITLE
Multi-cohort: survival curve data is not accurate after selecting subset of bar chart 

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/iViz#42]
![screen shot 2016-06-13 at 3 04 21 pm](https://cloud.githubusercontent.com/assets/5400599/16019680/228e3772-3178-11e6-9ba9-22e3062ed10e.png)

**Comment by zhx828** [comment]
The bar chart should only shows selected region as blue

**Comment by yichaoS** [comment]
mouseover data is not accurate after selecting subset of bar chart, init curve color with wrong color, selected curve not starting from zero points
