### ISSUE TITLE
Group.top is not a function

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/iViz#508]
![may-22-2017 13-19-59](https://cloud.githubusercontent.com/assets/5400599/26320607/631bc390-3ef1-11e7-8ba2-dc85da17af7e.gif)

@kalletlak did you see the issue locally?
And it only appears if user selects genes from table after initially loaded the page

**Comment by kalletlak** [comment]
No. Everything works ok to me

**Comment by zhx828** [comment]
Looks like this is data issue
