### ISSUE TITLE
# of patients/samples are incorrect after deselecting one row in the table

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/iViz#512]
This issue exists in production code and only apply to pie table.
![may-23-2017 10-13-29](https://cloud.githubusercontent.com/assets/5400599/26358408/7f8103ce-3fa0-11e7-9ab8-2e0e27b5773f.gif)

**Comment by kalletlak** [comment]
@zhx828 I think its fixed. Unable to reproduce it. Closing it for now.
