### ISSUE TITLE
for virtual cohorts, 'all' case list does not include all

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/iViz#536]
Steps to reproduce:

Go to acc_tcga study summary, make a virtual cohort out of the male patients (there are 31), query it using the 'All' case list, and you should see an oncoprint with only 29.

I tried manually pasting in the 31 sample ids from the virtual cohort into custom case list, and that worked, it did give me all of them. So it seems to be a problem with the All case list.

**Comment by jjgao** [comment]
Is this due to the fact that we only query sequenced and cna-profiled samples?

**Comment by adamabeshouse** [comment]
what was the resolution to this? @zhx828
