### ISSUE TITLE
Use study oncotree code if a sample has none

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/iViz#553]
... to populate CANCER_TYPE and CANCER_TYPE_DETAILED.

Should we do this in the frontend or backend? Maybe backend because we need it everywhere.

If backend, should we fix the data in the database, ie. modify importer. Or change the web API (business layer)?

**Comment by jjgao** [comment]
This issue depends on https://github.com/cBioPortal/cbioportal/issues/2763

**Comment by zhx828** [comment]
Potentially use study meta which includes OncoTree code

**Comment by zhx828** [comment]
This will be a data fix
