### ISSUE TITLE
display study id in the url

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/iViz#554]
Real id if it is a real study. Virtual id if a virtual is created.

**Comment by adamabeshouse** [comment]
@jjgao but I don't think a cohort is created instantly if you go to a multiple-study summary from the query form. That's the case that I switched away from URL parameters for - in case too many studies.

**Comment by jjgao** [comment]
@adamabeshouse if there is only a few studies (real or virtual), say 20 or less, can we display the IDs. If there are more, let's use a post.

In the long run, we should have session for the study view page which can remember the study ids and other states.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/2992/files
