### ISSUE TITLE
Study url normalization

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/iViz#560]
- [x] support `study` and `study.do`. By default `study` should be used in all the link in the portal. `study.do` is just for backward compatibility.
- [x] for parameters, let's support `study?id=`. We should still support `study?cancer_study_id=` just for backward compatibility. Let's remove `study?cohorts=`
  - [x] change links to use `id` instead of `cohorts`
  - [x] do not support `cohorts`

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/2992/files
