### ISSUE TITLE
Query for virtual study with multiple studies not work

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/iViz#563]
http://www.cbioportal.org/alpha/index.do?session_id=596e323e498e5df2e292ab50

![image](https://user-images.githubusercontent.com/840895/28329598-68ec481e-6bb8-11e7-8ae7-3c3926b8102e.png)

**Comment by jjgao** [comment]
I think we have three options.

1. always include study_id when query from study view
1. include study_id when query a virtual study from study view
1. include study_id when query a virtual study with only one *real* study

`#1` is probably the easiest. How difficult is `#2` and `#2`?

**Comment by adamabeshouse** [comment]
does 'include' mean 'autofill', or 'require the user to include'?

**Comment by jjgao** [comment]
I mean when query directly from study view page, automatically add the study_id.

**Comment by adamabeshouse** [comment]
I don't see any issues when I click through the link you gave, it is including the study id automatically. I believe it will always populate it automatically with the study ids.

**Comment by adamabeshouse** [comment]
to reproduce:

go to multiple study summary
save virtual cohort
go to that virtual cohort summary
query from there

**Comment by jjgao** [comment]
It looks like it's fixed.
