### ISSUE TITLE
CancerTypeSummary tab error

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/iViz#565]
http://www.cbioportal.org/alpha/index.do?session_id=596e596d498e5df2e292ae06&show_samples=false&

![image](https://user-images.githubusercontent.com/840895/28339774-4609b0fc-6bdb-11e7-8f70-198eb48bba32.png)

**Comment by adamabeshouse** [comment]
this has to do with when sample ids are the same across studies, in this case the error occurs for a sample used in both `blca_tcga` and `blca_tcga_pub`. Fix upcoming

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/2992/files
