### ISSUE TITLE
Clinical attribute id same as the predefined ids

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/iViz#574]
If the clinical attribute id from the backend is the same in the predefined ids, then the chart will be shown as empty but functional...

http://www.cbioportal.org/study?id=prad_fhcrc#summary
![screen shot 2017-07-28 at 5 49 42 pm](https://user-images.githubusercontent.com/5400599/28737589-35754ef6-73bd-11e7-9dfc-4a0b5980d7ef.png)

**Comment by kalletlak** [comment]
@zhx828 seems working now, closing.
