### ISSUE TITLE
mutations tab: mutation table

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/iViz#590]
should add study_id column if virtual cohort/multiple studies selected? @jjgao

**Comment by jjgao** [comment]
Yes. maybe `Cancer Study` column with the cancer study names (truncated if too long similar to `Cancer Type` column).

I thought there was already some implementation. @onursumer ?

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/590
