### ISSUE TITLE
add CANCER STUDY as an option for clinical track in oncoprint

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/iViz#604]

**Comment by adamabeshouse** [comment]
would users know to look for that? is that a "clinical" property?

**Comment by jjgao** [comment]
@adamabeshouse I couldn't think of a better place to put. We also display it as a chart in the study view. I think it's fine unless you have a better idea.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/3060
