### ISSUE TITLE
Remove "Virtual Studies" category in query page before we can save them into user's profile

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/iViz#608]
Based on feedback from Niki and Ethan.

Currently, we save them in local storage, which will not be loaded for the same user on different browsers or after they clear cookie.

For the first release, the user has to maintain their own list of virtual studies somewhere. Once we can support loading data by user, we can turn the "Virtual Studies" category back in.

In public portal, we don't have user login available -- we will need to implement that, maybe a frontend login just to get an ID or email address.

Here is the work to do:

- [x] Do not save virtual studies to local storage, or at least not show them in the query page.
- [x] Change the "save" button in study view to "share" button. Click on share button will display the the URL to the virtual study. We can keep the view button.
- [x] select real studies in modify query 
- [x] hide "My Virtual Study" category 
- [x] select real studies in main query page

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/589

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/3066/files

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/3081
