### ISSUE TITLE
mutual exclusivity tab doesn't load content

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/iViz#613]
Go here:
http://www.cbioportal.org/alpha/index.do?session_id=59a985ce498e5df2e294bd14&show_samples=false&

Click on Mutual Exclusivity and get this:
![image](https://user-images.githubusercontent.com/10508276/29980798-478721b0-8f19-11e7-8d94-c5d796df0097.png)

**Comment by kalletlak** [comment]
I think its fixed in latest version http://www.cbioportal.org/index.do?session_id=59a985ce498e5df2e294bd14&show_samples=false&
