### ISSUE TITLE
Study name disappear 

### ISSUE THREAD

**Issue by victoria34** [cBioPortal/iViz#630]
Two study cases don't have name on master branch.
![image](https://user-images.githubusercontent.com/14971266/31684220-fd6d790a-b34c-11e7-8cc1-d28ea6757c0c.png)

**Comment by jjgao** [comment]
@ritikakundra could you look into this? It's in the private portal.

**Comment by kalletlak** [comment]
@jjgao Is this resolved?. And I think its related to data issue

**Comment by ritikakundra** [comment]
@kalletlak Yes this has been fixed
