### ISSUE TITLE
set priority for showing charts

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/iViz#79]

**Comment by zhx828** [comment]
Survival > Scatter > Tables > Pie(Cancer Type, Cancer Type Details)

**Comment by zhx828** [comment]
We may need to assign different priority even within same chart type (edited)

Take MSKIMPACT as example, we want to show Cancer Type and Cancer Type Details as first two charts, but they are pie charts.

If we only assign same priority within same type, they will never be treated as first two
