### ISSUE TITLE
Rainbow survival curves

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/iViz#80]

**Comment by zhx828** [comment]
- [ ] Survival for Pie Chart
- [ ] Survival for Bar Chart
- [ ] Survival for Tables
- [ ] Survival tooltip

**Comment by zhx828** [comment]
Question:
- Should there be a threshold on how many groups are allowed in rainbow survival? Example: Other Sample ID; (Currently we only have 212 different colors can be assigned)
- Rainbow survival for tables? I can see the use case for Cancer (detailed) types, but is there any use case for MutatedGeneTable/CNA table?
